#!/bin/bash

DOCKER_HUB_USER=
DOCKER_HUB_PASS=
DOCKER_HUB_EMAIL=

DOCKER_SECRET_NAME=docker-io-secret

export DOCKER_HUB_USER DOCKER_HUB_PASS DOCKER_HUB_EMAIL DOCKER_SECRET_NAME

DB_HOST=10.1.1.1
DB_PORT=1521
DB_SID=oradb
DB_USER=oracle
DB_PASS=oracle

export DB_HOST DB_PORT DB_SID DB_USER DB_PASS

FILESERVER_IP=
FILESERVER_PORT=8080

export FILESERVER_IP FILESERVER_PORT

